// <auto-generated />
using System;
using GestionActivos.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionActivos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251110233711_RemoveCategoriaColumn")]
    partial class RemoveCategoriaColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionActivos.Domain.Entities.Activo", b =>
                {
                    b.Property<int>("IdActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdActivo"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Donacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Activo");

                    b.Property<string>("Etiqueta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Factura")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaAdquisicion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaAlta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("ImagenUrl");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("PortaEtiqueta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ResponsableId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ValorAdquisicion")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("IdActivo");

                    b.HasIndex("Etiqueta")
                        .IsUnique()
                        .HasFilter("[Etiqueta] IS NOT NULL");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("ResponsableId");

                    b.ToTable("MOV_ACTIVO", (string)null);
                });

            modelBuilder.Entity("GestionActivos.Domain.Entities.Auditoria", b =>
                {
                    b.Property<int>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAuditoria"));

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdAuditor")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioAuditado")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdAuditoria");

                    b.HasIndex("IdAuditor");

                    b.HasIndex("IdUsuarioAuditado");

                    b.ToTable("MOV_AUDITORIA", (string)null);
                });

            modelBuilder.Entity("GestionActivos.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCategoria");

                    b.ToTable("CAT_CATEGORIA", (string)null);
                });

            modelBuilder.Entity("GestionActivos.Domain.Entities.CentroCosto", b =>
                {
                    b.Property<int>("IdCentroCosto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCentroCosto"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Area")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdCentroCosto");

                    b.ToTable("CAT_CENTRO_COSTO", (string)null);
                });

            modelBuilder.Entity("GestionActivos.Domain.Entities.ConfigAuditoria", b =>
                {
                    b.Property<int>("IdConfig")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConfig"));

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdResponsable")
                        .HasColumnType("int");

                    b.Property<string>("Periodo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdConfig");

                    b.HasIndex("IdResponsable");

                    b.ToTable("CAT_CONFIG_AUDITORIA", (string)null);
                });

            modelBuilder.Entity("GestionActivos.Domain.Entities.DetalleAuditoria", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<string>("Comentarios")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdActivo")
                        .HasColumnType("int");

                    b.Property<int>("IdAuditoria")
                        .HasColumnType("int");

                    b.HasKey("IdDetalle");

                    b.HasIndex("IdActivo");

                    b.HasIndex("IdAuditoria");

                    b.ToTable("H_DETALLE_AUDITORIA", (string)null);
                });

            modelBuilder.Entity("GestionActivos.Domain.Entities.Diagnostico", b =>
                {
                    b.Property<int>("IdDiagnostico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDiagnostico"));

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdActivo")
                        .HasColumnType("int");

                    b.Property<int>("IdTecnico")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pieza")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("SugerirBaja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("TramiteGarantia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("ValorAdquisicion")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("IdDiagnostico");

                    b.HasIndex("IdActivo");

                    b.HasIndex("IdTecnico");

                    b.ToTable("MOV_DIAGNOSTICO", (string)null);
                });

            modelBuilder.Entity("GestionActivos.Domain.Entities.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPermiso"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdPermiso");

                    b.ToTable("CAT_PERMISO", (string)null);
                });

            modelBuilder.Entity("GestionActivos.Domain.Entities.Reubicacion", b =>
                {
                    b.Property<int>("IdReubicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReubicacion"));

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdActivo")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioAnterior")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioNuevo")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdReubicacion");

                    b.HasIndex("IdActivo");

                    b.HasIndex("IdUsuarioAnterior");

                    b.HasIndex("IdUsuarioNuevo");

                    b.ToTable("H_REUBICACION", (string)null);
                });

            modelBuilder.Entity("GestionActivos.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRol");

                    b.ToTable("CAT_ROL", (string)null);
                });

            modelBuilder.Entity("GestionActivos.Domain.Entities.RolPermiso", b =>
                {
                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int>("IdPermiso")
                        .HasColumnType("int");

                    b.HasKey("IdRol", "IdPermiso");

                    b.HasIndex("IdPermiso");

                    b.ToTable("CAT_ROL_PERMISO", (string)null);
                });

            modelBuilder.Entity("GestionActivos.Domain.Entities.Solicitud", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitud"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdEmisor")
                        .HasColumnType("int");

                    b.Property<int>("IdReceptor")
                        .HasColumnType("int");

                    b.Property<string>("Mensaje")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdSolicitud");

                    b.HasIndex("IdEmisor");

                    b.HasIndex("IdReceptor");

                    b.ToTable("MOV_SOLICITUD", (string)null);
                });

            modelBuilder.Entity("GestionActivos.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClaveFortia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("IdCentroCosto")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("ClaveFortia")
                        .IsUnique()
                        .HasFilter("[ClaveFortia] IS NOT NULL");

                    b.HasIndex("IdCentroCosto");

                    b.ToTable("CAT_USUARIO", (string)null);
                });

            modelBuilder.Entity("GestionActivos.Domain.Entities.UsuarioRol", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario", "IdRol");

                    b.HasIndex("IdRol");

                    b.ToTable("MOV_USUARIO_ROL", (string)null);
                });

            modelBuilder.Entity("GestionActivos.Domain.Entities.Activo", b =>
                {
                    b.HasOne("GestionActivos.Domain.Entities.Categoria", "CategoriaNavigation")
                        .WithMany("Activos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionActivos.Domain.Entities.Usuario", "Responsable")
                        .WithMany("ActivosResponsables")
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaNavigation");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("GestionActivos.Domain.Entities.Auditoria", b =>
                {
                    b.HasOne("GestionActivos.Domain.Entities.Usuario", "Auditor")
                        .WithMany()
                        .HasForeignKey("IdAuditor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionActivos.Domain.Entities.Usuario", "UsuarioAuditado")
                        .WithMany()
                        .HasForeignKey("IdUsuarioAuditado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auditor");

                    b.Navigation("UsuarioAuditado");
                });

            modelBuilder.Entity("GestionActivos.Domain.Entities.ConfigAuditoria", b =>
                {
                    b.HasOne("GestionActivos.Domain.Entities.Usuario", "Responsable")
                        .WithMany()
                        .HasForeignKey("IdResponsable")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("GestionActivos.Domain.Entities.DetalleAuditoria", b =>
                {
                    b.HasOne("GestionActivos.Domain.Entities.Activo", "Activo")
                        .WithMany("DetallesAuditoria")
                        .HasForeignKey("IdActivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionActivos.Domain.Entities.Auditoria", "Auditoria")
                        .WithMany("Detalles")
                        .HasForeignKey("IdAuditoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activo");

                    b.Navigation("Auditoria");
                });

            modelBuilder.Entity("GestionActivos.Domain.Entities.Diagnostico", b =>
                {
                    b.HasOne("GestionActivos.Domain.Entities.Activo", "Activo")
                        .WithMany("Diagnosticos")
                        .HasForeignKey("IdActivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionActivos.Domain.Entities.Usuario", "Tecnico")
                        .WithMany("Diagnosticos")
                        .HasForeignKey("IdTecnico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activo");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("GestionActivos.Domain.Entities.Reubicacion", b =>
                {
                    b.HasOne("GestionActivos.Domain.Entities.Activo", "Activo")
                        .WithMany("Reubicaciones")
                        .HasForeignKey("IdActivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionActivos.Domain.Entities.Usuario", "UsuarioAnterior")
                        .WithMany("ReubicacionesAnteriores")
                        .HasForeignKey("IdUsuarioAnterior")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionActivos.Domain.Entities.Usuario", "UsuarioNuevo")
                        .WithMany("ReubicacionesNuevas")
                        .HasForeignKey("IdUsuarioNuevo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activo");

                    b.Navigation("UsuarioAnterior");

                    b.Navigation("UsuarioNuevo");
                });

            modelBuilder.Entity("GestionActivos.Domain.Entities.RolPermiso", b =>
                {
                    b.HasOne("GestionActivos.Domain.Entities.Permiso", "Permiso")
                        .WithMany("Roles")
                        .HasForeignKey("IdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionActivos.Domain.Entities.Rol", "Rol")
                        .WithMany("Permisos")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("GestionActivos.Domain.Entities.Solicitud", b =>
                {
                    b.HasOne("GestionActivos.Domain.Entities.Usuario", "Emisor")
                        .WithMany("SolicitudesEmitidas")
                        .HasForeignKey("IdEmisor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionActivos.Domain.Entities.Usuario", "Receptor")
                        .WithMany("SolicitudesRecibidas")
                        .HasForeignKey("IdReceptor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Emisor");

                    b.Navigation("Receptor");
                });

            modelBuilder.Entity("GestionActivos.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("GestionActivos.Domain.Entities.CentroCosto", "CentroCosto")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdCentroCosto")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CentroCosto");
                });

            modelBuilder.Entity("GestionActivos.Domain.Entities.UsuarioRol", b =>
                {
                    b.HasOne("GestionActivos.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionActivos.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Roles")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionActivos.Domain.Entities.Activo", b =>
                {
                    b.Navigation("DetallesAuditoria");

                    b.Navigation("Diagnosticos");

                    b.Navigation("Reubicaciones");
                });

            modelBuilder.Entity("GestionActivos.Domain.Entities.Auditoria", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("GestionActivos.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Activos");
                });

            modelBuilder.Entity("GestionActivos.Domain.Entities.CentroCosto", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("GestionActivos.Domain.Entities.Permiso", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("GestionActivos.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Permisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("GestionActivos.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("ActivosResponsables");

                    b.Navigation("Diagnosticos");

                    b.Navigation("ReubicacionesAnteriores");

                    b.Navigation("ReubicacionesNuevas");

                    b.Navigation("Roles");

                    b.Navigation("SolicitudesEmitidas");

                    b.Navigation("SolicitudesRecibidas");
                });
#pragma warning restore 612, 618
        }
    }
}
